spring:
  mvc:
    throw-exception-if-no-handler-found: true
  webflux:
    static-path-pattern: /stub/data/**

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
